# Generated by Django 4.2.4 on 2023-08-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="image",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="students",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
