# Generated by Django 4.2.4 on 2023-08-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_students_image_alter_students_address"),
    ]

    operations = [
        migrations.RemoveField(model_name="students", name="image",),
    ]
