# Generated by Django 4.2.4 on 2023-08-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipe", "0004_subject_studentmarks"),
    ]

    operations = [
        migrations.RenameModel(old_name="StudentMarks", new_name="SubjectsMark",),
    ]
