# Generated by Django 4.2.4 on 2023-08-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0002_alter_imageuploader_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageuploader",
            name="photo",
            field=models.ImageField(upload_to="photofolder"),
        ),
    ]
